import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ProveedoresProductosServiciosI } from '../../../../interfaces/panel-control/proveedores-productos-servicios/proveedores-productos-servicios.interface';
import { TiposDocumentosIdentificacionI } from '../../../../interfaces/tipos-documentos-identificacion/tipos-documentos-identificacion.interface';
import { ProveedoresProductosServiciosService } from '../../../../services/panel-control/proveedores-productos-servicios/proveedores-productos-servicios.service';
import { TiposDocumentosIdentificacionService } from '../../../../services/tipos-documentos-identificacion/tipos-documentos-identificacion.service';
import { SemaforoContadoresComponent } from '../../../../shared/components/semaforo-contadores/semaforo-contadores.component';
import { AddUpdDelProveedorProductoServicioComponent } from '../add-upd-del-proveedor-producto-servicio/add-upd-del-proveedor-producto-servicio.component';
import { VistaProveedorProductoServicioComponent } from '../vista-proveedor-producto-servicio/vista-proveedor-producto-servicio.component';

@Component({selector:'app-listado-proveedores-productos-servicios',standalone:true,imports:[CommonModule,ReactiveFormsModule,SemaforoContadoresComponent,AddUpdDelProveedorProductoServicioComponent,VistaProveedorProductoServicioComponent],templateUrl:'./listado-proveedores-productos-servicios.component.html',styleUrl:'./listado-proveedores-productos-servicios.component.scss'})
export class ListadoProveedoresProductosServiciosComponent implements OnInit {
  private readonly fb=inject(FormBuilder); readonly form=this.fb.group({keyword:[''],estado:[''],cantidad:['10']}); registros:ProveedoresProductosServiciosI[]=[]; tipos:TiposDocumentosIdentificacionI[]=[]; total=0;activos=0;inactivos=0;pagina=0;cantidad=10;modal=false;vista=false;modo:'guardar'|'modificar'|'eliminar'='guardar';seleccionado:ProveedoresProductosServiciosI|null=null;toast='';tipoToast:'exito'|'error'='exito';
  constructor(private service:ProveedoresProductosServiciosService,private tiposService:TiposDocumentosIdentificacionService,private cdr:ChangeDetectorRef){}
  ngOnInit(){this.tiposService.findAllTypesOfIdentificationDocuments(undefined,undefined,'nombreTipoDocumentoIdentificacion','ASC').subscribe(x=>this.tipos=x);this.listar();}
  listar(){const v=this.form.getRawValue(),k=v.keyword?.trim()||undefined,e=v.estado||undefined;this.service.findAllProductOrServiceProvidersPag(this.pagina,this.cantidad,undefined,e,k,'idProveedorProductoOServicio','ASC').subscribe(x=>{this.registros=x;this.cdr.markForCheck();});this.service.findCountTotalRegisters(undefined,e,k).subscribe(x=>{this.total=x;this.cdr.markForCheck();});this.service.findCountTotalRegisters(undefined,'ACTIVO',k).subscribe(x=>{this.activos=x;this.cdr.markForCheck();});this.service.findCountTotalRegisters(undefined,'INACTIVO',k).subscribe(x=>{this.inactivos=x;this.cdr.markForCheck();});}
  buscar(){this.pagina=0;this.listar();} cambiarCantidad(){this.cantidad=Number(this.form.value.cantidad);this.buscar();} paginas(){return Math.max(1,Math.ceil(this.total/this.cantidad));} cambiarPagina(p:number){this.pagina=p;this.listar();} abrir(m:'guardar'|'modificar'|'eliminar',x:ProveedoresProductosServiciosI|null=null){this.modo=m;this.seleccionado=x;this.modal=true;} ver(x:ProveedoresProductosServiciosI){this.seleccionado=x;this.vista=true;} cerrar(){this.modal=false;this.vista=false;this.seleccionado=null;}
  guardar(x:ProveedoresProductosServiciosI){const mod=!!x.idProveedorProductoOServicio;(mod?this.service.updateProductOrServiceProvider(x):this.service.addProductOrServiceProvider(x)).subscribe({next:r=>{this.mostrar('exito',r.mensaje||(mod?'Proveedor modificado correctamente.':'Proveedor creado correctamente.'));this.cerrar();this.listar();},error:e=>this.mostrar('error',e.error?.mensaje||'No fue posible guardar el proveedor.')});} eliminar(id:number){this.service.deleteProductOrServiceProvider(id).subscribe({next:r=>{this.mostrar('exito',r.mensaje||'Proveedor eliminado correctamente.');this.cerrar();this.listar();},error:e=>this.mostrar('error',e.error?.mensaje||'No fue posible eliminar el proveedor.')});} private mostrar(t:'exito'|'error',m:string){this.tipoToast=t;this.toast=m;this.cdr.markForCheck();setTimeout(()=>{this.toast='';this.cdr.markForCheck();},4000);}
}
