export interface EmailsI {
    //DATOS DEL REMITENTE:
    authEnable: boolean;//PERMITE SI O NO ACTIVAR EN VERDADERO O FALSO (TRUE OR FALSE) LA AUTENTICACIÓN SMTP CON USUARIO Y PASSWORD.
    startTTLSEnable: boolean;//PERMITE SI O NO ACTIVAR EN VERDADERO O FALSO (TRUE OR FALSE) EL CIFRADO DE LA CONEXIÓN.
    smtpHost: String;//ESPECÍFICA LA DIRECCIÓN DEL SERVIDOR SMTP AL QUE SE CONECTARÁ PARA ENVIAR LOS CORREOS ELECTRÓNICOS.
    smtpPort: number;//ESPECÍFICA EL PUERTO DEL SERVIDOR SMTP AL QUE SE CONECTARÁ PARA ENVIAR LOS CORREOS ELECTRÓNICOS.
    smtpProtocols: String;//ESPECÍFICA LOS PROTOCOLOS SSL/TLS CON SU VERSIÓN QUE SE DEBEN DE USAR PARA ENVIAR LOS CORREOS ELECTRÓNICOS.
    correoElectronicoRemitente: String;//ESPECÍFICA EL CORREO ELECTRÓNICO DEL REMITENTE.
    usuarioRemitente: String;//ESPECÍFICA EL USUARIO REMITENTE (NICKNAME O CORREO ELECTRÓNICO DEL REMITENTE).
    passwordRemitente: String;//ESPECÍFICA EL PASSWORD REMITENTE.
    
    //DATOS DEL DESTINATARIO:
    correoElectronicoDestinatario: String;//ESPECÍFICA EL CORREO ELECTRÓNICO DEL DESTINATARIO.
    asuntoDestinatario: String;//ESPECÍFICA EL ASUNTO DEL DESTINATARIO.
    cuerpoMensajeHtml: String;//ESPECÍFICA EL CUERPO DEL MENSAJE HTML.
}

export interface EmailsMsj {
    mensaje: string;
}