//MISMO CONTRATO QUE EmailDTO DEL BACKEND (PATRÓN SIGEPS): SOLO VIAJAN EL ID DEL USUARIO Y EL MEDIO DE ENVÍO.
//EL BACKEND RESUELVE EL CORREO DE DESTINO, EL NÚMERO DE DOCUMENTO, EL CÓDIGO DE ACTIVACIÓN VIGENTE, LA PLANTILLA
//HTML Y LA CONFIGURACIÓN SMTP DESDE LA BASE DE DATOS; NINGUNO DE ESOS DATOS PASA POR EL NAVEGADOR.
export interface EmailsI {
    idUsuario: number;
    medioEnvio: 'INSTITUCIONAL' | 'PERSONAL';
}

export interface EmailsMsj {
    mensaje: string;
}
